name = "CryptoSignatures"
uuid = "35cc5888-0c46-470e-89c7-eafcaf79a1aa"
authors = ["akels <akels14@gmail.com>"]
version = "0.1.0"

[deps]
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
Paillier = "84e01822-a062-59e4-8289-aa032edeecdd"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
